<?php
/* LiangLee Framework
 * FrameWork for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @author Liang Lee
 * @copyright Copyright 2012, Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File Start.php
 */

 
elgg_register_event_handler('init', 'system', 'LiangleeFramework_init');
/*
 * Register Plugin Settings
 *
 * @access admin
 */
function LiangleeFramework_init() {
/*
 * Register Css
 *
 * @access public
 */
elgg_extend_view('css/elgg', 'LiangleeFramework/css');

}
/*
 * Inlude a view file
 *
 * @param Directory or path
 * @plugin Plugin Name
 * @access admin
 */  
function LiangLee_view($plugin, $params) {
if(is_file(elgg_get_plugins_path().$plugin.'/views/default/'.$plugin.'/'.$params.'.php')){
          include(elgg_get_plugins_path().$plugin.'/views/default/'.$plugin.'/'.$params.'.php');
          } else {
          if (elgg_is_admin_logged_in()){ 
          register_error(elgg_echo('lianglee:cant:load:view'));
          } else{
          register_error(elgg_echo('lianglee:cant:load:view:code'));	
        }           
    }
}
/*
 * Inlude a custom file
 *
 * @param Directory or path
 * @path Path to a file
 * @access admin
 */
function LiangLee_include($params, $path){
if(is_file(elgg_get_plugins_path().$params.'/'.$path.'.php')){
          include(elgg_get_plugins_path().$params.'/'.$path.'.php');
	      } else {
          if (elgg_is_admin_logged_in()){ 
          register_error(elgg_echo('lianglee:requested:file:not:found'));
          } else {
          register_error(elgg_echo('lianglee:requested:file:not:found:code'));	
        }           
    }
}
/*
 * Get Version 
 * @return returen if values does not match
 * @param Plugin Name
 * @access admin
 */
function LiangLee_version($params){
    static $LiangLee_version;
	if (!isset($LiangLee_version)) {
			if (!include(elgg_get_plugins_path() . $params."/version.php")) {
				return false;
			}
		}
	return $LiangLee_version;
}
/*
 * Get release
 * @return returen if values does not match
 * @param Plugin Name
 */
function LiangLee_release($params){
    static $LiangLee_release;
	if (!isset($LiangLee_release)) {
			if (!include(elgg_get_plugins_path() . $params."/version.php")) {
				return false;
			}
		}
	return $LiangLee_release;
}

/*
 * Inlcuding a class
 *
 * @filename File Name
 */
function LiangLee_Class($plugin, $params) {
if(is_file(elgg_get_plugins_path().$plugin.'/classes/'.$params.'.php')){
        include(elgg_get_plugins_path().$plugin.'/classes/'.$params.'.php');
        } else {
        if (elgg_is_admin_logged_in()){ 
        register_error(elgg_echo('lianglee:class:bad'));
        } else{
        register_error(elgg_echo('lianglee:class:bad:code'));	
       }            
    }
}
/*
 * Adding js to pages 
 *
 * @jsname Name of specfic js file
 * @access public
 */
ffunction LiangLee_inc_js($params,$jsname) {
if (isset($params) || isset($jsname)) {
         $path = "mod/".$params."/vendors/";
         $javas = "<script type=\"text/javascript\" src=\"".elgg_get_site_url().$path.$jsname."\"></script>\n";
	 return $javas;
	 } else {
	 if (elgg_is_admin_logged_in()) {
         register_error(elgg_echo('lianglee:cant:load:js'));
         } else {
        register_error(elgg_echo('lianglee:cant:load:js:code'));	
          }
       }
} 
/*
 * Adding css to pages 
 *
 * @cssname Name of specfic css file
 * @access public
 */
function LiangLee_inc_css($params ,$cssname) {
if (isset($params) || isset($cssname)) {
        $path = "mod/".$params."/";
        $style ="<link rel=\"stylesheet\" href=\"".elgg_get_site_url().$path.$cssname."\" type=\"text/css\" />\n";
        return $style;
	} else {
        if (elgg_is_admin_logged_in()) {
        register_error(elgg_echo('lianglee:cant:load:css'));
        } else {
        register_error(elgg_echo('lianglee:cant:load:css:code'));	
        }

    }
}
/*
 * Adding img in html
 *
 * @imgname Name of specfic image file
 * @access public
 */
function LiangLee_img($params,$picname){
if (isset($params) || isset($picname)) {
        $path = "mod/".$params."/media/";
	$image = "<img src=\"".elgg_get_site_url().$path.$picname."\">\n";
        return $image;
	} else {
	if (elgg_is_admin_logged_in()) {
        register_error(elgg_echo('lianglee:cant:load:img'));
        } else {
        register_error(elgg_echo('lianglee:cant:load:img:code'));	
        }

   }
}
/*
 * Server and execution environment information
 *
 * $HTTP_SERVER_VARS contains the same initial information, but is not a superglobal. (Note that
 * $HTTP_SERVER_VARS and $_SERVER are different variables and that PHP handles them as such).
 * @method server method
 * @access public
 */
function LiangLee_server($param){
if(isset($param)){
         $exe = $_SERVER[$param];
         return $exe;
         } else {
         if (elgg_is_admin_logged_in()) { 
         register_error(elgg_echo('lianglee:server:method:error'));
	 } else {
         register_error(elgg_echo('lianglee:server:method:error:code'));	
            }
	}  
}	
?>