<?php
/* LiangLeeFramework
 * @website Link: http://community.elgg.org/pg/profile/arsalanlee/
 * @package LiangLeeFramework
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2012.
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File version.php
 */
$LiangLee_version = 16012013;
$LiangLee_release = '1.1.4'; 
?>