<?php
/** LiangLeeFramework
 * @package Liang Lee Framework
 * @subpackage LiangLeePage.Class
 * @author Liang Lee
 * @copyright LIANG LEE 2012
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File LiangLeePage.php
 */
 defined('C_LEE_EXEC') or die ('Restricted access');  

/**
 * A class that create a new page
 * @uses: Examples;
 */
class LiangLeePage {

/**
* Setup of new page.
* $params['handler'] defualt page handler , mostly use $handler.
* $params['file'] page source file
* $params['page'] page name e.g <handler>/<page>
*/
function Lianglee_framework_pagehandler(array $params){
	switch ($params['handler']) {
		case $params['page']:
			require_once($params['file']);
	break;
		default:
			return false;
	}
	return true;
}
/**
* Construct new page.
* $params['handler'] defualt page handler , mostly use $handler.
* $params['file'] page source file
* $params['page'] page name e.g <handler>/<page>
* @todo : b0f8b49f22c718e9924f5b1165111a67
*/
public function construct($params){
       return $this->Lianglee_framework_pagehandler($params);
}

}
