<?php
/** LiangLeeFramework
 * @package Liang Lee Framework
 * @subpackage LiangLeePage.Class
 * @author Liang Lee
 * @copyright LIANG LEE 2012
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File LiangLeeUser.php
 */
 defined('C_LEE_EXEC') or die ('Restricted access');  

/**
 * A class show user data.
 * @uses: Examples;
 */
class LiangLeeUser {
/**
* Show a loggedin entity guid
* @uses  examples;
* @access: system;
*/
public function currentEntityGuid(){
$fetch = elgg_get_logged_in_user_entity()->guid;
if(!empty($fetch)){
       return $fetch;
   }
}
public function currentEntityName(){
$fetch = elgg_get_logged_in_user_entity()->name;
if(!empty($fetch)){
       return $fetch;
   }
}
public function currentEntityTimeIcon(){
$fetch = elgg_get_logged_in_user_entity()->icontime;
if(!empty($fetch)){
       return $fetch;
	   }
}
public function currentEntityUsername(){
$fetch = elgg_get_logged_in_user_entity()->username;
if(!empty($fetch)){
       return $fetch;
	   }
}
 
}