<?php
/** LiangLeeFramework
 * @package Liang Lee Framework
 * @subpackage LiangLeePage.Class
 * @author Liang Lee
 * @copyright LIANG LEE 2012
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File LiangLeeForm.php
 */
defined('C_LEE_EXEC') or die ('Restricted access');  

/**
 * A class that is use to create ajax form encode forms request.
 * @uses: Examples;
 */
class LiangLeeForm {
/**
* Encode text to base64
* @uses  examples;
* @access: system;
*/
public function encodeBase64($params){
       return lee_framework_encode_64($params);
}
/**
* Get seetings
* @uses  examples;
* @access: system;
*/
public function getSettings($params){
       return lee_framework_get_options($params);
}
/**
* Set user settings
* @uses  examples;
* @access: system;
*/
public function setSettings($params){
       return lianglee_set_usersettings($params);
}
/**
* Set a ajax form
* @uses  examples;
* @access: system;
*/
public function setAjax($settings = array()){
       return lee_set_ajax_submit($settings);
}
/**
* Remove a specific word from sentence
* @uses  examples;
* @access: system;
*/
public function removeString($string, $remove){
       return lee_framework_remove($string, $remove);
}

}