<?php
/** LiangLeeFramework
 * @package Liang Lee Framework
 * @subpackage LiangLeePage.Class
 * @author Liang Lee
 * @copyright LIANG LEE 2012
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File LiangLeePath.php
 */
 defined('C_LEE_EXEC') or die ('Restricted access');  

/**
 * A class that shows a path
 * @uses: Examples;
 */
class LiangLeePath {
/**
* Show a site actions path
* @uses  examples;
* @access: system;
*/
public function action($mod){
       return LiangLee_plugin_path($mod, 'actions');
}
/**
* Show a site css path
* @uses  examples;
* @access: system;
*/
public function css($mod){
       return LiangLee_plugin_path($mod , 'css');
}
/**
* Show a site lib path
* @uses  examples;
* @access: system;
*/
public function lib($mod){
       return LiangLee_plugin_path($mod , 'lib');
}
/**
* Show a site pages path
* @uses  examples;
* @access: system;
*/
public function pages($mod){
       return LiangLee_plugin_path($mod , 'pages');
}
/**
* Show a site vendors path
* @uses  examples;
* @access: system;
*/
public function vendors($mod){
       return LiangLee_plugin_path($mod , 'vendors');
}
/**
* Show a site doc path
* @uses  examples;
* @access: system;
*/
public function doc($mod){
       return LiangLee_plugin_path($mod , 'documentation');
}
/**
* Show a site classes path
* @uses  examples;
* @access: system;
*/
public function classes($mod){
       return LiangLee_plugin_path($mod , 'classes');
}
/**
* Show a site Media path
* @uses  examples;
* @access: system;
*/
public function media($mod){
       return LiangLee_plugin_path($mod , 'media');
}
/**
* Show a site preview path
* @uses  examples;
* @access: system;
*/
public function preview($mod){
       return LiangLee_plugin_path($mod , 'preview');
}
/**
* Show a site views/default path
* @uses  examples;
* @access: system;
*/
public function views($mod){
       return LiangLee_plugin_path($mod , 'preview').'default/';
}


}