<?php
/** LiangLeeFramework
 * @package Liang Lee Framework
 * @subpackage LiangLeePage.Class
 * @author Liang Lee
 * @copyright LIANG LEE 2012
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File LiangLeeFile.php
 */
 defined('C_LEE_EXEC') or die ('Restricted access');  

/**
 * A class that shows files / write files
 * @uses: Examples;
 */
class LiangLeeFile {
/**
* Write a file
* @uses  examples;
* @access: system;
*/
public function write($file, $data){
       return LiangLee_putconents($mod, $data);
}

/**
* Backup a file
* @uses  examples;
* @access: system;
*/
public function backup($params = array()){
       return LiangLee_backup($params);
}

}