<?php
/** LiangLeeFramework
 * @package Liang Lee Framework
 * @subpackage LiangLeePage.Class
 * @author Liang Lee
 * @copyright LIANG LEE 2012
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File LiangLeeSite.php
 */
 defined('C_LEE_EXEC') or die ('Restricted access');  

/**
 * A class that shows a site settings
 * @uses: Examples;
 */
class LiangLeeSite {
/**
* Show a site host
* @uses  examples;
* @access: system;
*/
public function getHost(){
       return Lianglee_get_my_elgg('hosts');
}
/**
* Show a site scheme
* @uses  examples;
* @access: system;
*/
public function getScheme(){
       return Lianglee_get_my_elgg('scheme');
}
/**
* Show a site path
* @uses  examples;
* @access: system;
*/
public function getSubpath(){
       return Lianglee_get_my_elgg('path');
}
/**
* Show a site connection
* @uses  examples;
* @access: system;
*/
public function getConnectionType(){
$fetch = Lianglee_get_connection();
if(!empty($fetch)){
        return $fetch;
    }
}
/**
* Show a site mod dir
* @uses  examples;
* @access: system;
*/
public function getDirMod(){
$fetch = elgg_get_plugins_path();
if(!empty($fetch)){
       return elgg_get_plugins_path();
    }
}
/**
* Show a site root dir
* @uses  examples;
* @access: system;
*/

public function getRoot(){
$fetch = elgg_get_root_path();
if(!empty($fetch)){
       return $fetch;
    }
  }
}