<?php
/** LiangLeeFramework
 * Block a username
 * @package LiangLeeFramework
 * @author Liang Lee
 * @copyright Copyright 2013, Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File lianglee.framework.pagesetup.php
 */
 
defined('_LEE_EXEC') or die ('Restricted access');  

/**
* Setup of new page.
* $params['handler'] defualt page handler , mostly use $handler.
* $params['file'] page source file
* $params['page'] page name e.g <handler>/<page>
*/
function Lianglee_framework_pagehandler(array $params){
	switch ($params['handler']) {
		case $params['page']:
			require_once($params['file']);
	break;
		default:
			return false;
	}
	return true;
}