<?php
/** LiangLeeFramework
 * Block a username
 * @package LiangLeeFramework
 * @author Liang Lee
 * @copyright Copyright 2013, Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File lianglee.framework.form.php
 */
 
defined('_LEE_EXEC') or die ('Restricted access');  

/**
 * Remove a word from a string
 *
 * @access system
 */ 
function lee_framework_encode_64($data = ''){ 
if(!empty($data)){
$data = base64_encode($data);
return lee_framework_remove($data, '=');
 }
} 
/**
 * Make a array from input
 *
 * @access system
 */

function lee_framework_get_options($settings){
if (is_string($settings)) {$options = explode(",", $settings);$options = array_map('trim', $options);
$options = array_filter($options, 'is_not_null');
  } return $options;	 
}	

/**
* Make a compactible with LiangLeePhpIde , used, array()
*/ 
function lianglee_set_usersettings($params = array()){
return elgg_set_plugin_user_setting(
         $params['name'], 
		 $params['value'] ,
		 $params['user_guid'], 
		 $params['plugin_id']
		 );
} 

/**
* Call a Ajax on form submit.
* $params['form_id'] id of form you are trying to make ajax.
* $params['type'] is form is GET or POST
* $params['process_id'] on sumbit its shows a image so the id of that div in which submit button is.
* $params['process_msg'] optional if want to show a message with  image.
*/ 
function lee_set_ajax_submit($params = array()){
if(!empty($params['form_id'])){
$path = LiangLee_plugin_path('LiangleeFramework','views').'default/lee/ajax/';
include($path.'lee_ajax_api.php');
   }
}
